name: 'Deb Signing'
description: 'Sign source and binary packages'
inputs:
  src-pkg-name:
    description: Name of the source package (`.source.changes` file)
    required: true
  bin-pkg-name:
    description: >
      Name of common part of the binary packages. Will append
      `*.changes` to select all binary packages
    required: true
  artifacts-prefix:
    description: Common prefix for the artifacts
    required: true
  artifacts-result-name:
    description: Name of the resulting artifacts store
    required: true
  gpg-signing-key:
    description: The base64 encoded private GPG key used to sign the packages
    required: true
  debsign-keyid:
    description: The public fingerprint of the GPG key used to sign the packages
    required: true
runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: |
        echo -e "::group::\e[32mInstall tools"
        export DEBIAN_FRONTEND=noninteractive
        export DEBIAN_PRIORITY=critical
        export DEBCONF_NOWARNINGS=yes
        sudo apt-get update
        sudo apt-get install -q -y devscripts equivs
        echo "::endgroup::"

    - name: Configure GPG Key
      shell: bash
      run: |
        echo -e "::group::\e[32mConfigure GPG key"
        echo -n "${{ inputs.gpg-signing-key }}" | base64 --decode | gpg --import
        echo "${{ inputs.debsign-keyid }}:6:" | gpg --import-ownertrust
        echo "::endgroup::"

    - name: Download Artifacts
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        pattern: ${{ inputs.artifacts-prefix }}*
        merge-multiple: true

    - name: Sign source package
      shell: bash
      run: |
        echo -e "::group::\e[32mSign source package"
        debsign -k${{ inputs.debsign-keyid }} --re-sign ${{ inputs.src-pkg-name }}
        echo "::endgroup::"

    - name: Sign binary packages
      shell: bash
      run: |
        echo -e "::group::\e[32mSign binary packages"
        debsign -k${{ inputs.debsign-keyid }} --re-sign ${{ inputs.bin-pkg-name }}*.changes
        echo "::endgroup::"

    - name: Store signed packages
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: ${{ inputs.artifacts-result-name }}
        path: ./**/*
